"""empty message

Revision ID: 59cd132e32e0
Revises: 11ea77decb90
Create Date: 2016-10-27 14:23:23.556527

"""

# revision identifiers, used by Alembic.
revision = '59cd132e32e0'
down_revision = '11ea77decb90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_item'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_item_name', 'item', ['name'], unique=False)
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_index('ix_item_name', table_name='item')
    op.drop_table('item')
    ### end Alembic commands ###
